<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Surefire test"
           tests="2"
           failures="1"
           errors="0"
           skipped="0"
           time="0.003">
    <properties></properties>

            <testcase
                name="testcase02"
                time="0.001"
                classname="com.TheTestingAcademy.ex_21092024.testngexamples.TestNG001">

            <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
                <![CDATA[java.lang.AssertionError: expected [false] but found [true]
                org.testng.Assert.fail(Assert.java:111)org.testng.Assert.failNotEquals(Assert.java:1578)org.testng.Assert.assertEqualsImpl(Assert.java:150)org.testng.Assert.assertEquals(Assert.java:132)org.testng.Assert.assertEquals(Assert.java:1067)org.testng.Assert.assertEquals(Assert.java:1031)org.testng.Assert.assertEquals(Assert.java:1077)com.TheTestingAcademy.ex_21092024.testngexamples.TestNG001.testcase02(TestNG001.java:24)java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)java.base/java.lang.reflect.Method.invoke(Method.java:580)org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)java.base/java.util.ArrayList.forEach(ArrayList.java:1597)org.testng.TestRunner.privateRun(TestRunner.java:739)org.testng.TestRunner.run(TestRunner.java:614)org.testng.SuiteRunner.runTest(SuiteRunner.java:421)org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)org.testng.SuiteRunner.run(SuiteRunner.java:312)org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)org.testng.TestNG.runSuitesLocally(TestNG.java:1208)org.testng.TestNG.runSuites(TestNG.java:1112)org.testng.TestNG.run(TestNG.java:1079)org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:155)org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:169)org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:88)org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:137)org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </failure>
    </testcase>


            <testcase
                name="testcase01"
                time="0.002"
                classname="com.TheTestingAcademy.ex_21092024.testngexamples.TestNG001">
            </testcase>
</testsuite>
